### PR TITLE
Erin's Media Ranker baseline - new rails app 

### PR DESCRIPTION
**Pull request by Erin007**
@CheezItMan @PilgrimMemoirs 

https://erin-media-ranker.herokuapp.com/

### CODE REVIEW

**Comment by kariabancroft** [comment]
Hi Erin! Just so you know, I think your GitHub account isn't set up correctly in the terminal. The commits on your PR should link to your github account, but it looks like they aren't :-( 

If you run: `git config --global -l`, you should see the e-mail that it's set up with and my guess is that isn't the e-mail address that you are set up with on github

**Comment by Erin007** [comment]
Gah! Thanks, Kari. I ran the config code you suggested, then set my primary
email on Github in my profile setting to the one listed in terminal. Did
that fix it?

**Comment by kariabancroft** [comment]
I think you should be able to tell if it fixed it the next time you see a commit on a PR or on your branch. It should have your Github picture on it with a link to your account.

**Comment by Erin007** [comment]
@CheezItMan @PilgrimMemoirs

https://erin-media-ranker.herokuapp.com/

**Pull request closed without merging**
